networks:
  rede.studio.caudas.express:
    driver: bridge
    
services:
  backend.studio.caudas.express:
    container_name: backend.studio.caudas.express
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
    - ./backend/:/app
    depends_on:
      -  mysql.studio.caudas.express
      -  redis.studio.caudas.express
    networks:
      - rede.studio.caudas.express

  mysql.studio.caudas.express:
    container_name: mysql.studio.caudas.express
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-backend}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USER:-username}
    volumes:
      - ./.storage/mysql:/var/lib/mysql
    networks:
      - rede.studio.caudas.express

  redis.studio.caudas.express:
    container_name: redis.studio.caudas.express
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./.storage/redis:/usr/local/etc/redis
    networks:
      - rede.studio.caudas.express